config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'nfl/:stat', to: 'nfl#show_stats', as: 'show_stats'
  post '/download-data', to: 'nfl#download_csv', as: 'download_csv'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/nfl_controller.rb
# Controller to handle NFL routing
class NflController < ApplicationController
  include Pagy::Backend
  before_action :set_data

  def show_stats
    @pagy, @data = pagy_array(@data) if @data
    @headers = @data[0].keys if @data
    @sortable_cols = %w[Yds Lng TD]
    @searchable_cols = ['Player']
  end

  def download_csv
    send_data NflApiService.to_csv(@data), filename: "player-#{Time.zone.today}.csv", disposition: 'attachment'
  end

  private

  def set_data
    @data = NflApiService.pull_stat_data(set_stat, set_sort, set_sort_col, set_search)
  end

  def set_stat
    @stat = params[:stat]
  end

  def set_sort
    @sort = params[:sort]
  end

  def set_sort_col
    @sort_col = params[:sort_col]
  end

  def set_search
    @search = params[:search]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NFL Stats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="container">
      <div class="logo"></div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/nfl/show_stats.html.erb
<% if @data %>
  <div class="input-group">
    <%= form_tag(download_csv_path(search: @search, sort: @sort, sort_col: @sort_col, stat: @stat), :method => "post", id: "search-form", class:'form-inline download') do %>
      <span class="input-group-btn">
        <%= submit_tag "Download CSV", class: 'btn btn-primary' %>
      </span>
    <% end %>
    <%= form_tag(show_stats_path, :method => "get", id: "search-form", class: 'form-inline') do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Player", class: 'form-control', value: @search %>
      <span class="input-group-btn">
        <%= submit_tag "Search", class: 'btn btn-primary' %>
      </span>
    <% end %>
  </div>
  <div class="table-responsive-md">
    <table id="table" class="table table-hover table-dark">
      <thead>
        <tr>
          <% @headers.each do |header| %>
            <th class=<%= header %>>
            <%= header %> 
            <% if @sortable_cols.include?(header)%> 
              <%= link_to "↑", show_stats_path(stat: @stat, sort: 'acs', sort_col: header, search: @search) %> 
              <%= link_to "↓", show_stats_path(stat: @stat, sort: 'desc', sort_col: header, search: @search) %> 
            <% end %>
            </th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @data.each do |data| %>
          <tr>
            <% @headers.each do |stat| %>
                <td>
                  <%= data[stat] %>
                </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <%== pagy_bootstrap_nav(@pagy) %>
<% else %>
  <div>
    <h2 class="no-stats">No data found for this stat</h2>
  </div>
<% end %>